[tools]
go = "1.26.3"
golangci-lint = "2.12.2"
goreleaser = "2.16.0"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.3.0"
"go:golang.org/x/tools/gopls" = "0.22.0"
pinact = "4.0.0"

[tasks.test]
description = "Run tests"
run = "go test -race ./... -v"

[tasks.lint]
description = "Lint the source code"
run = "golangci-lint run"

[tasks.vulncheck]
description = "Vulnerability checking"
run = "govulncheck ./..."

[tasks.release]
description = "Release a new version"
run = "goreleaser --clean"

[tasks.pinact]
description = "Update and pin GitHub Actions"
run = "pinact run -u"
